### ISSUE TITLE
Weird encoding of Windows file paths

### ISSUE THREAD

**Issue by hedefalk** [ensime/ensime-gradle#57] opened 2016-11-04 20:32 UTC
_From @cptaffe on November 4, 2016 20:9_

Unhandled promise rejection error on start.

```
Unhandled promise rejection Promise_bitField: 152305664_fulfillmentHandler0: Error: Invalid escape char P
    at LispReader.readString (C:\Users\cotaff\.atom\packages\Ensime\node_modules\ensime-client\release\js\lib\lisp\lisp.js:238:15)
    at LispReader.read (C:\Users\cotaff\.atom\packages\Ensime\node_modules\ensime-client\release\js\lib\lisp\lisp.js:184:17)
    at LispReader.readList (C:\Users\cotaff\.atom\packages\Ensime\node_modules\ensime-client\release\js\lib\lisp\lisp.js:220:30)
    at LispReader.read (C:\Users\cotaff\.atom\packages\Ensime\node_modules\ensime-client\release\js\lib\lisp\lisp.js:182:17)
    at Object.readFromString (C:\Users\cotaff\.atom\packages\Ensime\node_modules\ensime-client\release\js\lib\lisp\lisp.js:283:53)
    at C:\Users\cotaff\.atom\packages\Ensime\node_modules\ensime-client\release\js\lib\dotensime-utils.js:19:34
    at tryCatcher (C:\Users\cotaff\.atom\packages\Ensime\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\cotaff\.atom\packages\Ensime\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\cotaff\.atom\packages\Ensime\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\cotaff\.atom\packages\Ensime\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\cotaff\.atom\packages\Ensime\node_modules\bluebird\js\release\promise.js:691:18)
    at Promise._fulfill (C:\Users\cotaff\.atom\packages\Ensime\node_modules\bluebird\js\release\promise.js:636:18)
    at Promise._resolveCallback (C:\Users\cotaff\.atom\packages\Ensime\node_modules\bluebird\js\release\promise.js:431:57)
    at Promise._settlePromiseFromHandler (C:\Users\cotaff\.atom\packages\Ensime\node_modules\bluebird\js\release\promise.js:522:17)
    at Promise._settlePromise (C:\Users\cotaff\.atom\packages\Ensime\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\cotaff\.atom\packages\Ensime\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\cotaff\.atom\packages\Ensime\node_modules\bluebird\js\release\promise.js:691:18)
    at Promise._fulfill (C:\Users\cotaff\.atom\packages\Ensime\node_modules\bluebird\js\release\promise.js:636:18)
    at C:\Users\cotaff\.atom\packages\Ensime\node_modules\bluebird\js\release\nodeback.js:42:21
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)_promise0: undefined_receiver0: undefined_rejectionHandler0: undefined__proto__: Object with error: Error: Invalid escape char P
    at LispReader.readString (C:\Users\cotaff\.atom\packages\Ensime\node_modules\ensime-client\release\js\lib\lisp\lisp.js:238:15)
    at LispReader.read (C:\Users\cotaff\.atom\packages\Ensime\node_modules\ensime-client\release\js\lib\lisp\lisp.js:184:17)
    at LispReader.readList (C:\Users\cotaff\.atom\packages\Ensime\node_modules\ensime-client\release\js\lib\lisp\lisp.js:220:30)
    at LispReader.read (C:\Users\cotaff\.atom\packages\Ensime\node_modules\ensime-client\release\js\lib\lisp\lisp.js:182:17)
    at Object.readFromString (C:\Users\cotaff\.atom\packages\Ensime\node_modules\ensime-client\release\js\lib\lisp\lisp.js:283:53)
    at C:\Users\cotaff\.atom\packages\Ensime\node_modules\ensime-client\release\js\lib\dotensime-utils.js:19:34
    at tryCatcher (C:\Users\cotaff\.atom\packages\Ensime\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\cotaff\.atom\packages\Ensime\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\cotaff\.atom\packages\Ensime\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\cotaff\.atom\packages\Ensime\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\cotaff\.atom\packages\Ensime\node_modules\bluebird\js\release\promise.js:691:18)
    at Promise._fulfill (C:\Users\cotaff\.atom\packages\Ensime\node_modules\bluebird\js\release\promise.js:636:18)
    at Promise._resolveCallback (C:\Users\cotaff\.atom\packages\Ensime\node_modules\bluebird\js\release\promise.js:431:57)
    at Promise._settlePromiseFromHandler (C:\Users\cotaff\.atom\packages\Ensime\node_modules\bluebird\js\release\promise.js:522:17)
    at Promise._settlePromise (C:\Users\cotaff\.atom\packages\Ensime\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\cotaff\.atom\packages\Ensime\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\cotaff\.atom\packages\Ensime\node_modules\bluebird\js\release\promise.js:691:18)
    at Promise._fulfill (C:\Users\cotaff\.atom\packages\Ensime\node_modules\bluebird\js\release\promise.js:636:18)
    at C:\Users\cotaff\.atom\packages\Ensime\node_modules\bluebird\js\release\nodeback.js:42:21
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
```

_Copied from original issue: ensime/ensime-atom#257_

**Comment by hedefalk** [comment] 2016-11-04 20:32
_From @cptaffe on November 4, 2016 20:22_

Ah,

the `gradle` plugin doesn't handle Windows `\` appropriately by escaping them for paths like `java-home`, `source-roots`, `test-deps`, etc.

**Comment by hedefalk** [comment] 2016-11-04 20:32
Oh, ok! So, should we move to https://github.com/ensime/ensime-gradle? Can you post your .ensime just to make sure there's no issues with ensime-atom…

**Comment by hedefalk** [comment] 2016-11-04 20:32
_From @cptaffe on November 4, 2016 20:29_

Sure, now that we know it's an ensime-gradle issue.

Orginal [`.ensime`](https://github.com/ensime/ensime-atom/files/572580/ensime.txt)

**Comment by coacoas** [comment] 2016-12-17 19:29
This is a duplicate of #56.  I'm closing this one and will fix all with that issue.

**Closed by coacoas** 2016-12-17 19:29 UTC
